// `.env.ts` is generated by the `npm run env` command
import env from "./.env";

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: "/api",
  envName: "PROD",
  API_URL: "https://prodbff.loanhouse.us",
  LOCKDESK_API_URL : "https://lhposb2bbff1prod.loanhouse.us",
  QUICK_PRICER_API_URL : "https://lhposb2bbff1uat.loanhouse.us",
  is_taxonomy_static: false,
  is_zip_static: false,
  is_common_service_static: false,
  is_ob_service_static: false,
  is_floify_service_static: false,
  recapture_site_key: "6LfCHuMUAAAAADoTzhklZiSjcQLT1wZ7N_5g5hGy",
  DEFAULT_CREDIT_SCORE: 620,
  FRONT_END_URL : "https://b2c.loanhouse.us",
};
export const awsmobile = {

};
