// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from "./.env";

export const environment = {
  production: false,
  version: env.npm_package_version + "-test",
  serverUrl: "/api",
  envName: "DEV",
  API_URL: "http://localhost:8000",
  LOCKDESK_API_URL : "http://localhost:5000",
  QUICK_PRICER_API_URL : "https://lhposb2bbff1uat.loanhouse.us",
  is_taxonomy_static: true,
  is_zip_static: true,
  is_common_service_static: true,
  is_ob_service_static: true,
  is_floify_service_static: true,
  recapture_site_key: "6LdTHeMUAAAAAKfoUKnLaRxUx0jfBGGGYEYN7cw0",
  DEFAULT_CREDIT_SCORE: 620,
  FRONT_END_URL : "http://localhost:4200",
};
export const awsmobile = {

};
