//`.env.ts` is generated by the `npm run env` command
import env from "./.env";
export const environment = {
  production: false,
  version: env.npm_package_version,
  serverUrl: "/api",
  envName: "uat",
  API_URL: "https://uatbff.loanhouse.us",
  LOCKDESK_API_URL : "https://lhposb2bbff1uat.loanhouse.us",
  QUICK_PRICER_API_URL : "https://lhposb2bbff1uat.loanhouse.us",
  is_taxonomy_static: false,
  is_zip_static: false,
  is_common_service_static: false,
  is_ob_service_static: false,
  is_floify_service_static: false,
  recapture_site_key: "6LfCHuMUAAAAADoTzhklZiSjcQLT1wZ7N_5g5hGy",
  DEFAULT_CREDIT_SCORE: 620,
  FRONT_END_URL : "https://uatb2c.loanhouse.us",
};
const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:eaef3231-8a94-49fd-a5ce-ff19e584fe51",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_rkRVNSDU5",
  "aws_user_pools_web_client_id": "5jm1pvp2chi1pmg42f7bia7f19",
  "oauth": {},
  "aws_cognito_login_mechanisms": [
    "EMAIL"
  ],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ]
};

