//`.env.ts` is generated by the `npm run env` command
import env from "./.env";
export const environment = {
  production: false,
  version: env.npm_package_version,
  serverUrl: "/api",
  envName: "uat",
  API_URL: "https://uatbff.loanhouse.us",
  is_taxonomy_static: false,
  is_zip_static: false,
  is_common_service_static: false,
  is_ob_service_static: false,
  is_floify_service_static: false,
  recapture_site_key: "6LfCHuMUAAAAADoTzhklZiSjcQLT1wZ7N_5g5hGy",
  DEFAULT_CREDIT_SCORE: 620
};
